# Generated by Django 4.0.2 on 2022-04-16 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
