# Generated by Django 4.0.2 on 2022-04-16 07:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
